package com.gigatech.websocket;

public enum WebsocketErrors {
	TCP_CONNECT_ERROR,
	TCP_SEND_ERROR,
	TCP_DISCONNECT_ERROR,
	WEBSOCKET_HANDSHAKE_ERROR,
	WEBSOCKET_HANDSHAKE_RESPONSE_FIELD_ERROR,
	WEBSOCKET_SEND_ERROR,
	WEBSOCKET_RECEIVE_ERROR
}